### ISSUE TITLE
Add CurrentContext to the bash PS1

### ISSUE THREAD

**Issue by adamzhoul** [lfbear/k#1]
as the title said. so we know which cluster we are connecting now.

# How to do it 

1. kubectl config current-context 
2. set to an new env
3. update $PS1

**Comment by lfbear** [comment]
@adamzhoul Does this solve your question

**Comment by adamzhoul** [comment]
It's great.
But, how can I upgrade new version?

**Comment by adamzhoul** [comment]
exec: `curl https://raw.githubusercontent.com/lfbear/k/main/install.sh | bash` again?

**Comment by lfbear** [comment]
Update to new version:
exec:
```
curl -OL https://raw.githubusercontent.com/lfbear/k/main/k.sh 
chmod +x k.sh
cp -f k.sh ~/.kube/k.sh
```
